window.esdocSearchIndex = [
  [
    "gdax/lib/clients/authenticated.js~authenticatedclient",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html",
    "<span>AuthenticatedClient</span> <span class=\"search-result-import-path\">gdax/lib/clients/authenticated.js</span>",
    "class"
  ],
  [
    "gdax/lib/orderbook.js~orderbook",
    "class/lib/orderbook.js~OrderBook.html",
    "<span>OrderBook</span> <span class=\"search-result-import-path\">gdax/lib/orderbook.js</span>",
    "class"
  ],
  [
    "gdax/lib/orderbook_sync.js~orderbooksync",
    "class/lib/orderbook_sync.js~OrderBookSync.html",
    "<span>OrderBookSync</span> <span class=\"search-result-import-path\">gdax/lib/orderbook_sync.js</span>",
    "class"
  ],
  [
    "gdax/lib/clients/public.js~publicclient",
    "class/lib/clients/public.js~PublicClient.html",
    "<span>PublicClient</span> <span class=\"search-result-import-path\">gdax/lib/clients/public.js</span>",
    "class"
  ],
  [
    "gdax/lib/clients/websocket.js~websocketclient",
    "class/lib/clients/websocket.js~WebSocketClient.html",
    "<span>WebSocketClient</span> <span class=\"search-result-import-path\">gdax/lib/clients/websocket.js</span>",
    "class"
  ],
  [
    "authenticatedclient lib/clients/authenticated.js~authenticatedclient,authenticatedclient",
    "test-file/tests/authenticated.js.html#lineNumber28",
    "AuthenticatedClient",
    "test"
  ],
  [
    "authenticatedclient#_getsignature authenticatedclient#_getsignature,authenticatedclient#_getsignature",
    "test-file/tests/authenticated.js.html#lineNumber30",
    "AuthenticatedClient ._getSignature",
    "test"
  ],
  [
    "authenticatedclient#buy lib/clients/authenticated.js~authenticatedclient#buy,authenticatedclient#buy",
    "test-file/tests/authenticated.js.html#lineNumber147",
    "AuthenticatedClient buy order",
    "test"
  ],
  [
    "authenticatedclient#cancelallorders lib/clients/authenticated.js~authenticatedclient#cancelallorders,authenticatedclient#cancelallorders",
    "test-file/tests/authenticated.js.html#lineNumber221",
    "AuthenticatedClient cancel all orders",
    "test"
  ],
  [
    "authenticatedclient#cancelallorders lib/clients/authenticated.js~authenticatedclient#cancelallorders,authenticatedclient#cancelallorders",
    "test-file/tests/authenticated.js.html#lineNumber383",
    "AuthenticatedClient cancel all should be able to handle errors",
    "test"
  ],
  [
    "authenticatedclient#deposit lib/clients/authenticated.js~authenticatedclient#deposit,authenticatedclient#deposit",
    "test-file/tests/authenticated.js.html#lineNumber339",
    "AuthenticatedClient deposit",
    "test"
  ],
  [
    "authenticatedclient#getaccount lib/clients/authenticated.js~authenticatedclient#getaccount,authenticatedclient#getaccount",
    "test-file/tests/authenticated.js.html#lineNumber48",
    "AuthenticatedClient get account",
    "test"
  ],
  [
    "authenticatedclient#getaccounthistory lib/clients/authenticated.js~authenticatedclient#getaccounthistory,authenticatedclient#getaccounthistory",
    "test-file/tests/authenticated.js.html#lineNumber94",
    "AuthenticatedClient get account history",
    "test"
  ],
  [
    "authenticatedclient#getaccountholds lib/clients/authenticated.js~authenticatedclient#getaccountholds,authenticatedclient#getaccountholds",
    "test-file/tests/authenticated.js.html#lineNumber122",
    "AuthenticatedClient get account holds",
    "test"
  ],
  [
    "authenticatedclient#getaccounts lib/clients/authenticated.js~authenticatedclient#getaccounts,authenticatedclient#getaccounts",
    "test-file/tests/authenticated.js.html#lineNumber71",
    "AuthenticatedClient get accounts",
    "test"
  ],
  [
    "authenticatedclient#getfills lib/clients/authenticated.js~authenticatedclient#getfills,authenticatedclient#getfills",
    "test-file/tests/authenticated.js.html#lineNumber310",
    "AuthenticatedClient get fills",
    "test"
  ],
  [
    "authenticatedclient#getorders lib/clients/authenticated.js~authenticatedclient#getorders,authenticatedclient#getorders",
    "test-file/tests/authenticated.js.html#lineNumber274",
    "AuthenticatedClient get orders",
    "test"
  ],
  [
    "authenticatedclient#getproductorderbook lib/clients/authenticated.js~authenticatedclient#getproductorderbook,authenticatedclient#getproductorderbook",
    "test-file/tests/authenticated.js.html#lineNumber205",
    "AuthenticatedClient get product orderbook",
    "test"
  ],
  [
    "authenticatedclient#sell lib/clients/authenticated.js~authenticatedclient#sell,authenticatedclient#sell",
    "test-file/tests/authenticated.js.html#lineNumber176",
    "AuthenticatedClient sell order",
    "test"
  ],
  [
    "authenticatedclient#cancelorder lib/clients/authenticated.js~authenticatedclient#cancelorder,authenticatedclient#cancelorder",
    "test-file/tests/authenticated.js.html#lineNumber266",
    "AuthenticatedClient should require orderID for cancelOrder",
    "test"
  ],
  [
    "authenticatedclient#getorder lib/clients/authenticated.js~authenticatedclient#getorder,authenticatedclient#getorder",
    "test-file/tests/authenticated.js.html#lineNumber302",
    "AuthenticatedClient should require orderID for getOrder",
    "test"
  ],
  [
    "authenticatedclient#withdraw lib/clients/authenticated.js~authenticatedclient#withdraw,authenticatedclient#withdraw",
    "test-file/tests/authenticated.js.html#lineNumber361",
    "AuthenticatedClient withdraw",
    "test"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "orderbook lib/orderbook.js~orderbook,orderbook",
    "test-file/tests/orderbook.js.html#lineNumber23",
    "OrderBook",
    "test"
  ],
  [
    "orderbook#add lib/orderbook.js~orderbook#add,orderbook#add",
    "test-file/tests/orderbook.js.html#lineNumber25",
    "OrderBook add new orders",
    "test"
  ],
  [
    "orderbook#change lib/orderbook.js~orderbook#change,orderbook#change",
    "test-file/tests/orderbook.js.html#lineNumber163",
    "OrderBook full order match",
    "test"
  ],
  [
    "orderbook#get lib/orderbook.js~orderbook#get,orderbook#get",
    "test-file/tests/orderbook.js.html#lineNumber96",
    "OrderBook get order",
    "test"
  ],
  [
    "orderbook#add lib/orderbook.js~orderbook#add,orderbook#add",
    "test-file/tests/orderbook.js.html#lineNumber200",
    "OrderBook order change",
    "test"
  ],
  [
    "orderbook#match lib/orderbook.js~orderbook#match,orderbook#match",
    "test-file/tests/orderbook.js.html#lineNumber120",
    "OrderBook partial order match",
    "test"
  ],
  [
    "orderbook#remove lib/orderbook.js~orderbook#remove,orderbook#remove",
    "test-file/tests/orderbook.js.html#lineNumber52",
    "OrderBook remove order",
    "test"
  ],
  [
    "",
    "test-file/tests/public_client.js.html#lineNumber21",
    "get product trades",
    "test"
  ],
  [
    "lib/clients/authenticated.js",
    "file/lib/clients/authenticated.js.html",
    "lib/clients/authenticated.js",
    "file"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#b64secret",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-member-b64secret",
    "lib/clients/authenticated.js~AuthenticatedClient#b64secret",
    "member"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#buy",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-buy",
    "lib/clients/authenticated.js~AuthenticatedClient#buy",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#cancelallorders",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-cancelAllOrders",
    "lib/clients/authenticated.js~AuthenticatedClient#cancelAllOrders",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#cancelorder",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-cancelOrder",
    "lib/clients/authenticated.js~AuthenticatedClient#cancelOrder",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#cancelorders",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-cancelOrders",
    "lib/clients/authenticated.js~AuthenticatedClient#cancelOrders",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#constructor",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-constructor-constructor",
    "lib/clients/authenticated.js~AuthenticatedClient#constructor",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#delete",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-delete",
    "lib/clients/authenticated.js~AuthenticatedClient#delete",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#deposit",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-deposit",
    "lib/clients/authenticated.js~AuthenticatedClient#deposit",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#get",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-get",
    "lib/clients/authenticated.js~AuthenticatedClient#get",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#getaccount",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-getAccount",
    "lib/clients/authenticated.js~AuthenticatedClient#getAccount",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#getaccounthistory",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-getAccountHistory",
    "lib/clients/authenticated.js~AuthenticatedClient#getAccountHistory",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#getaccountholds",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-getAccountHolds",
    "lib/clients/authenticated.js~AuthenticatedClient#getAccountHolds",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#getaccounts",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-getAccounts",
    "lib/clients/authenticated.js~AuthenticatedClient#getAccounts",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#getfills",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-getFills",
    "lib/clients/authenticated.js~AuthenticatedClient#getFills",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#getorder",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-getOrder",
    "lib/clients/authenticated.js~AuthenticatedClient#getOrder",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#getorders",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-getOrders",
    "lib/clients/authenticated.js~AuthenticatedClient#getOrders",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#getproductorderbook",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-getProductOrderBook",
    "lib/clients/authenticated.js~AuthenticatedClient#getProductOrderBook",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#key",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-member-key",
    "lib/clients/authenticated.js~AuthenticatedClient#key",
    "member"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#passphrase",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-member-passphrase",
    "lib/clients/authenticated.js~AuthenticatedClient#passphrase",
    "member"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#post",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-post",
    "lib/clients/authenticated.js~AuthenticatedClient#post",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#put",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-put",
    "lib/clients/authenticated.js~AuthenticatedClient#put",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#request",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-request",
    "lib/clients/authenticated.js~AuthenticatedClient#request",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#sell",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-sell",
    "lib/clients/authenticated.js~AuthenticatedClient#sell",
    "method"
  ],
  [
    "lib/clients/authenticated.js~authenticatedclient#withdraw",
    "class/lib/clients/authenticated.js~AuthenticatedClient.html#instance-method-withdraw",
    "lib/clients/authenticated.js~AuthenticatedClient#withdraw",
    "method"
  ],
  [
    "lib/clients/public.js",
    "file/lib/clients/public.js.html",
    "lib/clients/public.js",
    "file"
  ],
  [
    "lib/clients/public.js~publicclient#addheaders",
    "class/lib/clients/public.js~PublicClient.html#instance-method-addHeaders",
    "lib/clients/public.js~PublicClient#addHeaders",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#apiuri",
    "class/lib/clients/public.js~PublicClient.html#instance-member-apiURI",
    "lib/clients/public.js~PublicClient#apiURI",
    "member"
  ],
  [
    "lib/clients/public.js~publicclient#constructor",
    "class/lib/clients/public.js~PublicClient.html#instance-constructor-constructor",
    "lib/clients/public.js~PublicClient#constructor",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#delete",
    "class/lib/clients/public.js~PublicClient.html#instance-method-delete",
    "lib/clients/public.js~PublicClient#delete",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#fetchtrades",
    "class/lib/clients/public.js~PublicClient.html#instance-method-fetchTrades",
    "lib/clients/public.js~PublicClient#fetchTrades",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#get",
    "class/lib/clients/public.js~PublicClient.html#instance-method-get",
    "lib/clients/public.js~PublicClient#get",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#getcurrencies",
    "class/lib/clients/public.js~PublicClient.html#instance-method-getCurrencies",
    "lib/clients/public.js~PublicClient#getCurrencies",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#getproduct24hrstats",
    "class/lib/clients/public.js~PublicClient.html#instance-method-getProduct24HrStats",
    "lib/clients/public.js~PublicClient#getProduct24HrStats",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#getproducthistoricrates",
    "class/lib/clients/public.js~PublicClient.html#instance-method-getProductHistoricRates",
    "lib/clients/public.js~PublicClient#getProductHistoricRates",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#getproductorderbook",
    "class/lib/clients/public.js~PublicClient.html#instance-method-getProductOrderBook",
    "lib/clients/public.js~PublicClient#getProductOrderBook",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#getproductticker",
    "class/lib/clients/public.js~PublicClient.html#instance-method-getProductTicker",
    "lib/clients/public.js~PublicClient#getProductTicker",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#getproducttradestream",
    "class/lib/clients/public.js~PublicClient.html#instance-method-getProductTradeStream",
    "lib/clients/public.js~PublicClient#getProductTradeStream",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#getproducttrades",
    "class/lib/clients/public.js~PublicClient.html#instance-method-getProductTrades",
    "lib/clients/public.js~PublicClient#getProductTrades",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#getproducts",
    "class/lib/clients/public.js~PublicClient.html#instance-method-getProducts",
    "lib/clients/public.js~PublicClient#getProducts",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#gettime",
    "class/lib/clients/public.js~PublicClient.html#instance-method-getTime",
    "lib/clients/public.js~PublicClient#getTime",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#makeabsoluteuri",
    "class/lib/clients/public.js~PublicClient.html#instance-method-makeAbsoluteURI",
    "lib/clients/public.js~PublicClient#makeAbsoluteURI",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#makerelativeuri",
    "class/lib/clients/public.js~PublicClient.html#instance-method-makeRelativeURI",
    "lib/clients/public.js~PublicClient#makeRelativeURI",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#makerequestcallback",
    "class/lib/clients/public.js~PublicClient.html#instance-method-makeRequestCallback",
    "lib/clients/public.js~PublicClient#makeRequestCallback",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#post",
    "class/lib/clients/public.js~PublicClient.html#instance-method-post",
    "lib/clients/public.js~PublicClient#post",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#productid",
    "class/lib/clients/public.js~PublicClient.html#instance-member-productID",
    "lib/clients/public.js~PublicClient#productID",
    "member"
  ],
  [
    "lib/clients/public.js~publicclient#put",
    "class/lib/clients/public.js~PublicClient.html#instance-method-put",
    "lib/clients/public.js~PublicClient#put",
    "method"
  ],
  [
    "lib/clients/public.js~publicclient#request",
    "class/lib/clients/public.js~PublicClient.html#instance-method-request",
    "lib/clients/public.js~PublicClient#request",
    "method"
  ],
  [
    "lib/clients/websocket.js",
    "file/lib/clients/websocket.js.html",
    "lib/clients/websocket.js",
    "file"
  ],
  [
    "lib/clients/websocket.js~websocketclient#connect",
    "class/lib/clients/websocket.js~WebSocketClient.html#instance-method-connect",
    "lib/clients/websocket.js~WebSocketClient#connect",
    "method"
  ],
  [
    "lib/clients/websocket.js~websocketclient#constructor",
    "class/lib/clients/websocket.js~WebSocketClient.html#instance-constructor-constructor",
    "lib/clients/websocket.js~WebSocketClient#constructor",
    "method"
  ],
  [
    "lib/clients/websocket.js~websocketclient#disconnect",
    "class/lib/clients/websocket.js~WebSocketClient.html#instance-method-disconnect",
    "lib/clients/websocket.js~WebSocketClient#disconnect",
    "method"
  ],
  [
    "lib/clients/websocket.js~websocketclient#onclose",
    "class/lib/clients/websocket.js~WebSocketClient.html#instance-method-onClose",
    "lib/clients/websocket.js~WebSocketClient#onClose",
    "method"
  ],
  [
    "lib/clients/websocket.js~websocketclient#onmessage",
    "class/lib/clients/websocket.js~WebSocketClient.html#instance-method-onMessage",
    "lib/clients/websocket.js~WebSocketClient#onMessage",
    "method"
  ],
  [
    "lib/clients/websocket.js~websocketclient#onopen",
    "class/lib/clients/websocket.js~WebSocketClient.html#instance-method-onOpen",
    "lib/clients/websocket.js~WebSocketClient#onOpen",
    "method"
  ],
  [
    "lib/clients/websocket.js~websocketclient#pinger",
    "class/lib/clients/websocket.js~WebSocketClient.html#instance-member-pinger",
    "lib/clients/websocket.js~WebSocketClient#pinger",
    "member"
  ],
  [
    "lib/clients/websocket.js~websocketclient#productid",
    "class/lib/clients/websocket.js~WebSocketClient.html#instance-member-productID",
    "lib/clients/websocket.js~WebSocketClient#productID",
    "member"
  ],
  [
    "lib/clients/websocket.js~websocketclient#socket",
    "class/lib/clients/websocket.js~WebSocketClient.html#instance-member-socket",
    "lib/clients/websocket.js~WebSocketClient#socket",
    "member"
  ],
  [
    "lib/clients/websocket.js~websocketclient#websocketuri",
    "class/lib/clients/websocket.js~WebSocketClient.html#instance-member-websocketURI",
    "lib/clients/websocket.js~WebSocketClient#websocketURI",
    "member"
  ],
  [
    "lib/orderbook.js",
    "file/lib/orderbook.js.html",
    "lib/orderbook.js",
    "file"
  ],
  [
    "lib/orderbook.js~orderbook#add",
    "class/lib/orderbook.js~OrderBook.html#instance-method-add",
    "lib/orderbook.js~OrderBook#add",
    "method"
  ],
  [
    "lib/orderbook.js~orderbook#change",
    "class/lib/orderbook.js~OrderBook.html#instance-method-change",
    "lib/orderbook.js~OrderBook#change",
    "method"
  ],
  [
    "lib/orderbook.js~orderbook#constructor",
    "class/lib/orderbook.js~OrderBook.html#instance-constructor-constructor",
    "lib/orderbook.js~OrderBook#constructor",
    "method"
  ],
  [
    "lib/orderbook.js~orderbook#get",
    "class/lib/orderbook.js~OrderBook.html#instance-method-get",
    "lib/orderbook.js~OrderBook#get",
    "method"
  ],
  [
    "lib/orderbook.js~orderbook#match",
    "class/lib/orderbook.js~OrderBook.html#instance-method-match",
    "lib/orderbook.js~OrderBook#match",
    "method"
  ],
  [
    "lib/orderbook.js~orderbook#remove",
    "class/lib/orderbook.js~OrderBook.html#instance-method-remove",
    "lib/orderbook.js~OrderBook#remove",
    "method"
  ],
  [
    "lib/orderbook.js~orderbook#state",
    "class/lib/orderbook.js~OrderBook.html#instance-method-state",
    "lib/orderbook.js~OrderBook#state",
    "method"
  ],
  [
    "lib/orderbook_sync.js",
    "file/lib/orderbook_sync.js.html",
    "lib/orderbook_sync.js",
    "file"
  ],
  [
    "lib/orderbook_sync.js~orderbooksync#apiuri",
    "class/lib/orderbook_sync.js~OrderBookSync.html#instance-member-apiURI",
    "lib/orderbook_sync.js~OrderBookSync#apiURI",
    "member"
  ],
  [
    "lib/orderbook_sync.js~orderbooksync#authenticatedclient",
    "class/lib/orderbook_sync.js~OrderBookSync.html#instance-member-authenticatedClient",
    "lib/orderbook_sync.js~OrderBookSync#authenticatedClient",
    "member"
  ],
  [
    "lib/orderbook_sync.js~orderbooksync#book",
    "class/lib/orderbook_sync.js~OrderBookSync.html#instance-member-book",
    "lib/orderbook_sync.js~OrderBookSync#book",
    "member"
  ],
  [
    "lib/orderbook_sync.js~orderbooksync#constructor",
    "class/lib/orderbook_sync.js~OrderBookSync.html#instance-constructor-constructor",
    "lib/orderbook_sync.js~OrderBookSync#constructor",
    "method"
  ],
  [
    "lib/orderbook_sync.js~orderbooksync#loadorderbook",
    "class/lib/orderbook_sync.js~OrderBookSync.html#instance-method-loadOrderBook",
    "lib/orderbook_sync.js~OrderBookSync#loadOrderBook",
    "method"
  ],
  [
    "lib/orderbook_sync.js~orderbooksync#onmessage",
    "class/lib/orderbook_sync.js~OrderBookSync.html#instance-method-onMessage",
    "lib/orderbook_sync.js~OrderBookSync#onMessage",
    "method"
  ],
  [
    "lib/orderbook_sync.js~orderbooksync#processmessage",
    "class/lib/orderbook_sync.js~OrderBookSync.html#instance-method-processMessage",
    "lib/orderbook_sync.js~OrderBookSync#processMessage",
    "method"
  ],
  [
    "lib/orderbook_sync.js~orderbooksync#productid",
    "class/lib/orderbook_sync.js~OrderBookSync.html#instance-member-productID",
    "lib/orderbook_sync.js~OrderBookSync#productID",
    "member"
  ],
  [
    "lib/orderbook_sync.js~orderbooksync#publicclient",
    "class/lib/orderbook_sync.js~OrderBookSync.html#instance-member-publicClient",
    "lib/orderbook_sync.js~OrderBookSync#publicClient",
    "member"
  ],
  [
    "lib/orderbook_sync.js~orderbooksync#websocketuri",
    "class/lib/orderbook_sync.js~OrderBookSync.html#instance-member-websocketURI",
    "lib/orderbook_sync.js~OrderBookSync#websocketURI",
    "member"
  ],
  [
    "",
    "test-file/tests/public_client.js.html#lineNumber49",
    "public client should return values",
    "test"
  ],
  [
    "",
    "test-file/tests/public_client.js.html#lineNumber71",
    "public client should stream trades",
    "test"
  ],
  [
    "",
    "test-file/tests/public_client.js.html#lineNumber92",
    "public client should stream trades with function",
    "test"
  ],
  [
    "tests/authenticated.js",
    "test-file/tests/authenticated.js.html",
    "tests/authenticated.js",
    "testFile"
  ],
  [
    "tests/orderbook.js",
    "test-file/tests/orderbook.js.html",
    "tests/orderbook.js",
    "testFile"
  ],
  [
    "tests/orderbook_sync_test.js",
    "test-file/tests/orderbook_sync_test.js.html",
    "tests/orderbook_sync_test.js",
    "testFile"
  ],
  [
    "tests/public_client.js",
    "test-file/tests/public_client.js.html",
    "tests/public_client.js",
    "testFile"
  ]
]